hrm/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :employees
    resources :memberships
    resources :langages
    resources :licenses
    resources :educations
    resources :qualifications
    resources :work_shifs
    resources :job_categories
    resources :employment_statuses
    resources :grades
    resources :job_titles
    resources :organizations
    resources :nationalities
    resources :users

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

hrm/app/models/education.rb
class Education < ApplicationRecord
end

hrm/app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :nationality
end

hrm/app/models/employment_status.rb
class EmploymentStatus < ApplicationRecord
end

hrm/app/models/grade.rb
class Grade < ApplicationRecord
end

hrm/app/models/job_category.rb
class JobCategory < ApplicationRecord
end

hrm/app/models/job_title.rb
class JobTitle < ApplicationRecord
end

hrm/app/models/langage.rb
class Langage < ApplicationRecord
end

hrm/app/models/license.rb
class License < ApplicationRecord
end

hrm/app/models/membership.rb
class Membership < ApplicationRecord
end

hrm/app/models/nationality.rb
class Nationality < ApplicationRecord
end

hrm/app/models/organization.rb
class Organization < ApplicationRecord
end

hrm/app/models/qualification.rb
class Qualification < ApplicationRecord
end

hrm/app/models/user.rb
class User < ApplicationRecord
end

hrm/app/models/work_shif.rb
class WorkShif < ApplicationRecord
end

hrm/app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: %i[ show edit update destroy ]

  # GET /grades or /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1 or /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades or /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to grade_url(@grade), notice: "Grade was successfully created." }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1 or /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to grade_url(@grade), notice: "Grade was successfully updated." }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1 or /grades/1.json
  def destroy
    @grade.destroy!

    respond_to do |format|
      format.html { redirect_to grades_url, notice: "Grade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grade_params
      params.require(:grade).permit(:name, :meta)
    end
end

hrm/app/helpers/educations_helper.rb
module EducationsHelper
end

hrm/app/helpers/employees_helper.rb
module EmployeesHelper
end

hrm/app/helpers/grades_helper.rb
module GradesHelper
end

hrm/app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

hrm/app/helpers/langages_helper.rb
module LangagesHelper
end

hrm/app/helpers/licenses_helper.rb
module LicensesHelper
end

hrm/app/helpers/users_helper.rb
module UsersHelper
end

hrm/app/helpers/work_shifs_helper.rb
module WorkShifsHelper
end

hrm/app/views/grades/_form.html.erb
<%= form_with(model: grade) do |form| %>
  <% if grade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
        <% grade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :meta, style: "display: block" %>
    <%= form.text_area :meta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hrm/app/views/grades/_grade.html.erb
<div id="<%= dom_id grade %>">
  <p>
    <strong>Name:</strong>
    <%= grade.name %>
  </p>

  <p>
    <strong>Meta:</strong>
    <%= grade.meta %>
  </p>

</div>

hrm/app/views/grades/edit.html.erb
<h1>Editing grade</h1>

<%= render "form", grade: @grade %>

<br>

<div>
  <%= link_to "Show this grade", @grade %> |
  <%= link_to "Back to grades", grades_path %>
</div>

hrm/app/views/grades/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Grades</h1>

<div id="grades">
  <% @grades.each do |grade| %>
    <%= render grade %>
    <p>
      <%= link_to "Show this grade", grade %>
    </p>
  <% end %>
</div>

<%= link_to "New grade", new_grade_path %>

hrm/app/views/grades/new.html.erb
<h1>New grade</h1>

<%= render "form", grade: @grade %>

<br>

<div>
  <%= link_to "Back to grades", grades_path %>
</div>

hrm/app/views/grades/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @grade %>

<div>
  <%= link_to "Edit this grade", edit_grade_path(@grade) %> |
  <%= link_to "Back to grades", grades_path %>

  <%= button_to "Destroy this grade", @grade, method: :delete %>
</div>