hrm/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :employees
    resources :memberships
    resources :langages
    resources :licenses
    resources :educations
    resources :qualifications
    resources :work_shifs
    resources :job_categories
    resources :employment_statuses
    resources :grades
    resources :job_titles
    resources :organizations
    resources :nationalities
    resources :users

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

hrm/app/models/education.rb
class Education < ApplicationRecord
end

hrm/app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :nationality
end

hrm/app/models/employment_status.rb
class EmploymentStatus < ApplicationRecord
end

hrm/app/models/grade.rb
class Grade < ApplicationRecord
end

hrm/app/models/job_category.rb
class JobCategory < ApplicationRecord
end

hrm/app/models/job_title.rb
class JobTitle < ApplicationRecord
end

hrm/app/models/langage.rb
class Langage < ApplicationRecord
end

hrm/app/models/license.rb
class License < ApplicationRecord
end

hrm/app/models/membership.rb
class Membership < ApplicationRecord
end

hrm/app/models/nationality.rb
class Nationality < ApplicationRecord
end

hrm/app/models/organization.rb
class Organization < ApplicationRecord
end

hrm/app/models/qualification.rb
class Qualification < ApplicationRecord
end

hrm/app/models/user.rb
class User < ApplicationRecord
end

hrm/app/models/work_shif.rb
class WorkShif < ApplicationRecord
end

hrm/app/controllers/job_categories_controller.rb
class JobCategoriesController < ApplicationController
  before_action :set_job_category, only: %i[ show edit update destroy ]

  # GET /job_categories or /job_categories.json
  def index
    @job_categories = JobCategory.all
  end

  # GET /job_categories/1 or /job_categories/1.json
  def show
  end

  # GET /job_categories/new
  def new
    @job_category = JobCategory.new
  end

  # GET /job_categories/1/edit
  def edit
  end

  # POST /job_categories or /job_categories.json
  def create
    @job_category = JobCategory.new(job_category_params)

    respond_to do |format|
      if @job_category.save
        format.html { redirect_to job_category_url(@job_category), notice: "Job category was successfully created." }
        format.json { render :show, status: :created, location: @job_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_categories/1 or /job_categories/1.json
  def update
    respond_to do |format|
      if @job_category.update(job_category_params)
        format.html { redirect_to job_category_url(@job_category), notice: "Job category was successfully updated." }
        format.json { render :show, status: :ok, location: @job_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_categories/1 or /job_categories/1.json
  def destroy
    @job_category.destroy!

    respond_to do |format|
      format.html { redirect_to job_categories_url, notice: "Job category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_category
      @job_category = JobCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_category_params
      params.require(:job_category).permit(:name, :meta)
    end
end

hrm/app/helpers/educations_helper.rb
module EducationsHelper
end

hrm/app/helpers/employees_helper.rb
module EmployeesHelper
end

hrm/app/helpers/grades_helper.rb
module GradesHelper
end

hrm/app/helpers/job_categories_helper.rb
module JobCategoriesHelper
end

hrm/app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

hrm/app/helpers/langages_helper.rb
module LangagesHelper
end

hrm/app/helpers/licenses_helper.rb
module LicensesHelper
end

hrm/app/helpers/users_helper.rb
module UsersHelper
end

hrm/app/views/job_categories/_form.html.erb
<%= form_with(model: job_category) do |form| %>
  <% if job_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_category.errors.count, "error") %> prohibited this job_category from being saved:</h2>

      <ul>
        <% job_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :meta, style: "display: block" %>
    <%= form.text_area :meta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hrm/app/views/job_categories/_job_category.html.erb
<div id="<%= dom_id job_category %>">
  <p>
    <strong>Name:</strong>
    <%= job_category.name %>
  </p>

  <p>
    <strong>Meta:</strong>
    <%= job_category.meta %>
  </p>

</div>

hrm/app/views/job_categories/edit.html.erb
<h1>Editing job category</h1>

<%= render "form", job_category: @job_category %>

<br>

<div>
  <%= link_to "Show this job category", @job_category %> |
  <%= link_to "Back to job categories", job_categories_path %>
</div>

hrm/app/views/job_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Job categories</h1>

<div id="job_categories">
  <% @job_categories.each do |job_category| %>
    <%= render job_category %>
    <p>
      <%= link_to "Show this job category", job_category %>
    </p>
  <% end %>
</div>

<%= link_to "New job category", new_job_category_path %>

hrm/app/views/job_categories/new.html.erb
<h1>New job category</h1>

<%= render "form", job_category: @job_category %>

<br>

<div>
  <%= link_to "Back to job categories", job_categories_path %>
</div>

hrm/app/views/job_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job_category %>

<div>
  <%= link_to "Edit this job category", edit_job_category_path(@job_category) %> |
  <%= link_to "Back to job categories", job_categories_path %>

  <%= button_to "Destroy this job category", @job_category, method: :delete %>
</div>