hrm/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :employees
    resources :memberships
    resources :langages
    resources :licenses
    resources :educations
    resources :qualifications
    resources :work_shifs
    resources :job_categories
    resources :employment_statuses
    resources :grades
    resources :job_titles
    resources :organizations
    resources :nationalities
    resources :users

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

hrm/app/models/education.rb
class Education < ApplicationRecord
end

hrm/app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :nationality
end

hrm/app/models/employment_status.rb
class EmploymentStatus < ApplicationRecord
end

hrm/app/models/grade.rb
class Grade < ApplicationRecord
end

hrm/app/models/job_category.rb
class JobCategory < ApplicationRecord
end

hrm/app/models/job_title.rb
class JobTitle < ApplicationRecord
end

hrm/app/models/langage.rb
class Langage < ApplicationRecord
end

hrm/app/models/license.rb
class License < ApplicationRecord
end

hrm/app/models/membership.rb
class Membership < ApplicationRecord
end

hrm/app/models/nationality.rb
class Nationality < ApplicationRecord
end

hrm/app/models/organization.rb
class Organization < ApplicationRecord
end

hrm/app/models/qualification.rb
class Qualification < ApplicationRecord
end

hrm/app/models/user.rb
class User < ApplicationRecord
end

hrm/app/models/work_shif.rb
class WorkShif < ApplicationRecord
end

hrm/app/controllers/admin/educations_controller.rb
class Admin::EducationsController < AdminController
  before_action :set_education, only: %i[ show edit update destroy ]

  # GET /educations or /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1 or /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations or /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to admin_educations_url, notice: "Education was successfully created." }
        format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1 or /educations/1.json
  def update
    respond_to do |format|
      if @education.update(admin_education_params)

        format.html { redirect_to admin_educations_url, notice: "Education was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1 or /educations/1.json
  def destroy
    @education.destroy!

    respond_to do |format|
      format.html { redirect_to admin_educations_url, notice: "Education was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def education_params
      params.require(:education).permit(:level, :meta)
    end
end

hrm/app/helpers/educations_helper.rb
module EducationsHelper
end

hrm/app/helpers/employees_helper.rb
module EmployeesHelper
end

hrm/app/helpers/grades_helper.rb
module GradesHelper
end

hrm/app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

hrm/app/helpers/langages_helper.rb
module LangagesHelper
end

hrm/app/helpers/licenses_helper.rb
module LicensesHelper
end

hrm/app/helpers/users_helper.rb
module UsersHelper
end

hrm/app/helpers/work_shifs_helper.rb
module WorkShifsHelper
end

hrm/app/views/admin/educations/_education.html.erb
<div id="<%= dom_id education %>">
  <p>
    <strong>Level:</strong>
    <%= education.level %>
  </p>

  <p>
    <strong>Meta:</strong>
    <%= education.meta %>
  </p>

</div>

hrm/app/views/admin/educations/_form.html.erb
<%= form_with(model: education, url: admin_educations_url) do |form| %>
  <% if education.errors.any? %>
    <div>
      <h2><%= pluralize(education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
        <% education.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Name", style: "display: block" %>
    <%= form.text_field :level, class: "form-control", placeholder:"Name", ariaLabel:"Username", ariaDescribedby:"basic-addon1" %>
  </div>

<br>
  <div>
    <%= form.label "Others", style: "display: block" %>
    <%= form.text_area :meta, class:"form-control", ariaLabel:"With textarea", placeholder:"Others" %>
  </div>

<br>

  <div>
  <%= form.submit "Save", class: "btn btn-primary" %>
</div>

<% end %>

hrm/app/views/admin/educations/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-white">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User Management
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
            <li><a class="dropdown-item" href="#">Users</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Jobs
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
            <li><a class="dropdown-item" href="#">Action 2.1</a></li>
            <li><a class="dropdown-item" href="#">Action 2.2</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Separated link 2</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Organization
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
            <li><a class="dropdown-item" href="#">Action 3.1</a></li>
            <li><a class="dropdown-item" href="#">Action 3.2</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Separated link 3</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown4" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Qualifications
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown4">
            <li><a class="dropdown-item" href="#">Skills</a></li>
            <li><a class="dropdown-item" href="#">Educations</a></li>
            <li><a class="dropdown-item" href="#">Languages</a></li>
            <li><a class="dropdown-item" href="#">Liceses</a></li>
            <li><a class="dropdown-item" href="#">Memberships</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown5" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Nationalities
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown5">
            <li><a class="dropdown-item" href="#">Action 5.1</a></li>
            <li><a class="dropdown-item" href="#">Action 5.2</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Separated link 5</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown5" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Corporate Branding
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown5">
            <li><a class="dropdown-item" href="#">Action 5.1</a></li>
            <li><a class="dropdown-item" href="#">Action 5.2</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Separated link 5</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown5" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Configuration
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown5">
            <li><a class="dropdown-item" href="#">Action 5.1</a></li>
            <li><a class="dropdown-item" href="#">Action 5.2</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Separated link 5</a></li>
          </ul>
        </li>

        
      </ul>
    </div>
  </div>
</nav>

hrm/app/views/admin/educations/edit.html.erb
<div class="container mt-4 mb-4  bg-white p-2 rounded">
  <h2>Editing Education</h2>
  <hr>
  <div class="input-group mb-3">
</div>
  <%= render "form", education: @education %>
</div>




<br>

<div> 
  |
  <%= link_to "Back to educations", admin_educations_path %>
</div>

hrm/app/views/admin/educations/index.html.erb
<%= render partial: 'navbar' %>
<br>
<p style="color: green"><%= notice %></p>

<div class="container mt-4 mb-4  bg-white p-2 rounded">
  <div class="row">
    <div class="col-6">
      <div>
        <h1>Educations</h1>
      </div>
    </div>
    <div class="col-6">
      <div class="text-end">
        <%= link_to "+ Add", new_admin_education_path, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<%# table to show education data %>
<div class="container mt-4">
  <table class="table table-bordered table-striped table-hover">
    <thead class="bg-secondary text-white">
      <tr>
        <th scope="col">Checkbox</th>
        <th scope="col">Name</th>
        <th scope="col">Delete</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody>
      <!-- Sample rows, you can add more as needed -->

 <% @educations.each do |education| %>
  <tr>
    <td><input type="checkbox"></td>
    <td>
      <%= education.level %>
    </td>
    <td>
   
     <%= button_to "Delete", admin_education_path(education), method: :delete, class: "btn btn-danger" %>

      </td>
    <td>
      <%= link_to "Edit", edit_admin_education_path(education), class:"btn btn-primary" %>
  </tr>
<% end %>


    </tbody>
  </table>
</div>

hrm/app/views/admin/educations/new.html.erb
<div class="container mt-4 mb-4  bg-white p-2 rounded">
<h1>New education</h1>
<hr>
<br>
<%= render "form", education: @education %>

<br>  
</div>



<div>
  <%= link_to "Back to educations", admin_educations_path %>
</div>

hrm/app/views/admin/educations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @education %>

<div>
  <%= link_to "Edit this education", edit_education_path(@education) %> |
  <%= link_to "Back to educations", educations_path %>

  <%= button_to "Destroy this education", @education, method: :delete %>
</div>