hrm/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :employees
    resources :memberships
    resources :langages
    resources :licenses
    resources :educations
    resources :qualifications
    resources :work_shifs
    resources :job_categories
    resources :employment_statuses
    resources :grades
    resources :job_titles
    resources :organizations
    resources :nationalities
    resources :users

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

hrm/app/models/education.rb
class Education < ApplicationRecord
end

hrm/app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :nationality
end

hrm/app/models/employment_status.rb
class EmploymentStatus < ApplicationRecord
end

hrm/app/models/grade.rb
class Grade < ApplicationRecord
end

hrm/app/models/job_category.rb
class JobCategory < ApplicationRecord
end

hrm/app/models/job_title.rb
class JobTitle < ApplicationRecord
end

hrm/app/models/langage.rb
class Langage < ApplicationRecord
end

hrm/app/models/license.rb
class License < ApplicationRecord
end

hrm/app/models/membership.rb
class Membership < ApplicationRecord
end

hrm/app/models/nationality.rb
class Nationality < ApplicationRecord
end

hrm/app/models/organization.rb
class Organization < ApplicationRecord
end

hrm/app/models/qualification.rb
class Qualification < ApplicationRecord
end

hrm/app/models/user.rb
class User < ApplicationRecord
end

hrm/app/models/work_shif.rb
class WorkShif < ApplicationRecord
end

hrm/app/controllers/langages_controller.rb
class LangagesController < ApplicationController
  before_action :set_langage, only: %i[ show edit update destroy ]

  # GET /langages or /langages.json
  def index
    @langages = Langage.all
  end

  # GET /langages/1 or /langages/1.json
  def show
  end

  # GET /langages/new
  def new
    @langage = Langage.new
  end

  # GET /langages/1/edit
  def edit
  end

  # POST /langages or /langages.json
  def create
    @langage = Langage.new(langage_params)

    respond_to do |format|
      if @langage.save
        format.html { redirect_to langage_url(@langage), notice: "Langage was successfully created." }
        format.json { render :show, status: :created, location: @langage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @langage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /langages/1 or /langages/1.json
  def update
    respond_to do |format|
      if @langage.update(langage_params)
        format.html { redirect_to langage_url(@langage), notice: "Langage was successfully updated." }
        format.json { render :show, status: :ok, location: @langage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @langage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /langages/1 or /langages/1.json
  def destroy
    @langage.destroy!

    respond_to do |format|
      format.html { redirect_to langages_url, notice: "Langage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_langage
      @langage = Langage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def langage_params
      params.require(:langage).permit(:name, :meta)
    end
end

hrm/app/helpers/educations_helper.rb
module EducationsHelper
end

hrm/app/helpers/employees_helper.rb
module EmployeesHelper
end

hrm/app/helpers/grades_helper.rb
module GradesHelper
end

hrm/app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

hrm/app/helpers/langages_helper.rb
module LangagesHelper
end

hrm/app/helpers/licenses_helper.rb
module LicensesHelper
end

hrm/app/helpers/users_helper.rb
module UsersHelper
end

hrm/app/helpers/work_shifs_helper.rb
module WorkShifsHelper
end

hrm/app/views/langages/_form.html.erb
<%= form_with(model: langage) do |form| %>
  <% if langage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(langage.errors.count, "error") %> prohibited this langage from being saved:</h2>

      <ul>
        <% langage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :meta, style: "display: block" %>
    <%= form.text_area :meta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hrm/app/views/langages/_langage.html.erb
<div id="<%= dom_id langage %>">
  <p>
    <strong>Name:</strong>
    <%= langage.name %>
  </p>

  <p>
    <strong>Meta:</strong>
    <%= langage.meta %>
  </p>

</div>

hrm/app/views/langages/edit.html.erb
<h1>Editing langage</h1>

<%= render "form", langage: @langage %>

<br>

<div>
  <%= link_to "Show this langage", @langage %> |
  <%= link_to "Back to langages", langages_path %>
</div>

hrm/app/views/langages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Langages</h1>

<div id="langages">
  <% @langages.each do |langage| %>
    <%= render langage %>
    <p>
      <%= link_to "Show this langage", langage %>
    </p>
  <% end %>
</div>

<%= link_to "New langage", new_langage_path %>

hrm/app/views/langages/new.html.erb
<h1>New langage</h1>

<%= render "form", langage: @langage %>

<br>

<div>
  <%= link_to "Back to langages", langages_path %>
</div>

hrm/app/views/langages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @langage %>

<div>
  <%= link_to "Edit this langage", edit_langage_path(@langage) %> |
  <%= link_to "Back to langages", langages_path %>

  <%= button_to "Destroy this langage", @langage, method: :delete %>
</div>